### ISSUE TITLE
Matrix multiplications don't always work.

### ISSUE THREAD

**Issue by jwidauer** [ethz-asl/eigen_catkin#16]
I suggest maybe changing to a higher version, since there seems to be a bug with matrix multiplications with transposed matrices, where they don't work and just halt the program.

The easiest snippet to reproduce this bug would be:
```
Eigen::MatrixXd test_mat = Eigen::Matrix3d::Identity();
Eigen::MatrixXd halting = Eigen::Matrix3d::Identity() * test_mat.transpose(); // <-- halts the program execution here
```

This seems to happen when one or both of the multiplied matrices is an `Eigen::MatrixXd` object and additionally `.transpose()` is called on the right multiplied matrix for the multiplication.

**Comment by HannesSommer** [comment]
I cannot confirm this. Neither with 3.2.7 nor 3.2.10 (using exactly your lines). With which version and compiler do you have the problem?

**Comment by jwidauer** [comment]
This is very weird...

I can't seem to replicate it anymore either. Even after trying the exact same thing as three days ago...

I use `c++14` and am using `gcc 5.4.0`. Had the problem with the current `Eigen` version used in this package, so `3.2.10`.

I guess it was some one time weird behaviour? Not sure, but seems to work alright now. Sorry for the inconvenience.

**Comment by HannesSommer** [comment]
No, problem. I'd suggest we close this here till this pops up again.
